# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openodonto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fp17ClinicalDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_and_polish', models.BooleanField(default=False)),
                ('fluoride_varnish', models.BooleanField(default=False)),
                ('fissure_sealants', models.IntegerField()),
                ('radiographs_taken', models.IntegerField()),
                ('endodontic_treatment', models.BooleanField(default=False)),
                ('permanent_fillings_and_sealant_restorations', models.IntegerField()),
                ('extractions', models.IntegerField()),
                ('crowns_provided', models.IntegerField()),
                ('upper_denture_acrylic', models.IntegerField()),
                ('lower_denture_acrylic', models.IntegerField()),
                ('upper_denture_metal', models.IntegerField()),
                ('lower_denture_metal', models.IntegerField()),
                ('veneers_applied', models.IntegerField()),
                ('inlays', models.IntegerField()),
                ('bridges_fitted', models.IntegerField()),
                ('referral_for_advanced_mandatory_services_band', models.IntegerField()),
                ('examination', models.BooleanField(default=False)),
                ('antibiotic_items_prescribed', models.IntegerField()),
                ('other_treatment', models.BooleanField(default=False)),
                ('best_practice_prevention_according_to_delivering_better_oral_health_offered', models.BooleanField(default=False)),
                ('decayed_teeth_permanent', models.IntegerField()),
                ('decayed_teeth_deciduous', models.IntegerField()),
                ('missing_teeth_permanent', models.IntegerField()),
                ('missing_teeth_deciduous', models.IntegerField()),
                ('filled_teeth_permanent', models.IntegerField()),
                ('filled_teeth_deciduous', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fp17Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necessary_care_provided', models.BooleanField(default=False)),
                ('necessary_care_carried_out', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=255)),
                ('signature_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fp17DentalCareProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_location_number', models.IntegerField()),
                ('provider_address', models.CharField(max_length=255)),
                ('performer_number_same_as_provider', models.BooleanField(default=False)),
                ('provider_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fp17Exemptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_under_18', models.BooleanField(default=False)),
                ('full_remission_hc2_cert', models.BooleanField(default=False)),
                ('partial_remission_hc3_cert', models.BooleanField(default=False)),
                ('expectant_mother', models.BooleanField(default=False)),
                ('nursing_mother', models.BooleanField(default=False)),
                ('aged_18_in_full_time_education', models.BooleanField(default=False)),
                ('income_support', models.BooleanField(default=False)),
                ('nhs_tax_credit_exemption', models.BooleanField(default=False)),
                ('income_based_jobseekers_allowance', models.BooleanField(default=False)),
                ('pension_credit_guarantee_credit', models.BooleanField(default=False)),
                ('prisoner', models.BooleanField(default=False)),
                ('income_related_employment_and_support_allowance', models.BooleanField(default=False)),
                ('universal_credit', models.BooleanField(default=False)),
                ('evidence_of_exception_or_remission_seen', models.BooleanField(default=False)),
                ('patient_charge_collected', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Fp17IncompleteTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomplete_treatment_band_1', models.BooleanField(default=False)),
                ('incomplete_treatment_band_2', models.BooleanField(default=False)),
                ('incomplete_treatment_band_3', models.BooleanField(default=False)),
                ('date_of_acceptance', models.DateField()),
                ('completion_same_as_acceptance_date', models.BooleanField(default=False)),
                ('completion_or_last_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fp17NHSBSAFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fp17_NHSBSA_field_1', models.CharField(max_length=255)),
                ('Fp17_NHSBSA_field_2', models.CharField(max_length=255)),
                ('Fp17_NHSBSA_field_3', models.CharField(max_length=255)),
                ('Fp17_NHSBSA_field_4', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Fp17OtherDentalServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_on_referral', models.BooleanField(default=False)),
                ('free_repair_or_replacement', models.BooleanField(default=False)),
                ('further_treatment_within_2_months', models.BooleanField(default=False)),
                ('domicillary_services', models.BooleanField(default=False)),
                ('sedation_services', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fp17TreatmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_category_band_1', models.BooleanField(default=False)),
                ('treatment_category_band_2', models.BooleanField(default=False)),
                ('treatment_category_band_3', models.BooleanField(default=False)),
                ('urgent_treatment', models.BooleanField(default=False)),
                ('regulation_11_replacement_appliance', models.BooleanField(default=False)),
                ('prescription_only', models.BooleanField(default=False)),
                ('denture_repairs', models.BooleanField(default=False)),
                ('bridge_repairs', models.BooleanField(default=False)),
                ('arrest_of_bleeding', models.BooleanField(default=False)),
                ('removal_of_sutures', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_months', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='demographics',
            name='city_or_town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographics',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographics',
            name='house_number_or_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographics',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
