# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openodonto', '0002_auto_20180301_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recall',
            new_name='Fp17Recall',
        ),
        migrations.RenameField(
            model_name='fp17dentalcareprovider',
            old_name='provider_number',
            new_name='performer_number',
        ),
        migrations.RenameField(
            model_name='fp17dentalcareprovider',
            old_name='performer_number_same_as_provider',
            new_name='performer_number_is_same_as_provider',
        ),
    ]
