# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openodonto', '0003_auto_20180301_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17clinicaldataset_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17clinicaldataset_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17declaration',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17declaration',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17declaration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17declaration_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17declaration',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17declaration',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17declaration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17declaration_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17dentalcareprovider_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17dentalcareprovider_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17exemptions',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17exemptions',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17exemptions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17exemptions_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17exemptions',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17exemptions',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17exemptions',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17exemptions_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17incompletetreatment',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17incompletetreatment',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17incompletetreatment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17incompletetreatment_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17incompletetreatment',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17incompletetreatment',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17incompletetreatment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17incompletetreatment_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17nhsbsafields',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17nhsbsafields',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17nhsbsafields',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17nhsbsafields_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17nhsbsafields',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17nhsbsafields',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17nhsbsafields',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17nhsbsafields_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17otherdentalservices',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17otherdentalservices',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17otherdentalservices',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17otherdentalservices_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17otherdentalservices',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17otherdentalservices',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17otherdentalservices',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17otherdentalservices_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17recall',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17recall',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17recall',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17recall_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17recall',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17recall',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17recall',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17recall_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17treatmentcategory',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17treatmentcategory',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17treatmentcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_openodonto_fp17treatmentcategory_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fp17treatmentcategory',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp17treatmentcategory',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fp17treatmentcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openodonto_fp17treatmentcategory_subrecords', to=settings.AUTH_USER_MODEL),
        ),
    ]
