# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='antibiotic_items_prescribed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='bridges_fitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='crowns_provided',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='decayed_teeth_deciduous',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='decayed_teeth_permanent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='extractions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='filled_teeth_deciduous',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='filled_teeth_permanent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='fissure_sealants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='inlays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='lower_denture_acrylic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='lower_denture_metal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='missing_teeth_deciduous',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='missing_teeth_permanent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='permanent_fillings_and_sealant_restorations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='radiographs_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='referral_for_advanced_mandatory_services_band',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='upper_denture_acrylic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='upper_denture_metal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='veneers_applied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17declaration',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fp17declaration',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='performer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='provider_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='provider_location_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fp17exemptions',
            name='patient_charge_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fp17incompletetreatment',
            name='completion_or_last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17incompletetreatment',
            name='date_of_acceptance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fp17nhsbsafields',
            name='Fp17_NHSBSA_field_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fp17nhsbsafields',
            name='Fp17_NHSBSA_field_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fp17nhsbsafields',
            name='Fp17_NHSBSA_field_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fp17nhsbsafields',
            name='Fp17_NHSBSA_field_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fp17recall',
            name='number_of_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
