# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-04 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0002_auto_20180301_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fp17dentalcareprovider',
            name='performer_number_is_same_as_provider',
        ),
        migrations.RemoveField(
            model_name='fp17incompletetreatment',
            name='completion_same_as_acceptance_date',
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='performer_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='provider_location_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
