# Generated by Django 2.0.9 on 2019-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0004_investigation_rhinovirus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosis / Issues', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='investigation',
            options={'verbose_name': 'Investigations'},
        ),
        migrations.AlterModelOptions(
            name='pastmedicalhistory',
            options={'verbose_name': 'PMH', 'verbose_name_plural': 'Past medical histories'},
        ),
        migrations.AlterModelOptions(
            name='patientconsultation',
            options={'verbose_name': 'Patient Consultation'},
        ),
        migrations.AlterModelOptions(
            name='symptomcomplex',
            options={'verbose_name': 'Symptoms', 'verbose_name_plural': 'Symptom complexes'},
        ),
        migrations.AlterField(
            model_name='allergies',
            name='drug_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='provisional',
            field=models.BooleanField(default=False, help_text='True if the allergy is only suspected. Defaults to False.', verbose_name='Suspected?'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='birth_place_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Death'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='death_indicator',
            field=models.BooleanField(default=False, help_text='This field will be True if the patient is deceased.'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='ethnicity_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='gp_practice_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='GP Practice Code'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='hospital_number',
            field=models.CharField(blank=True, help_text='The unique identifier for this patient at the hospital.', max_length=255),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='marital_status_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='nhs_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NHS Number'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='sex_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='title_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='condition_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='provisional',
            field=models.BooleanField(default=False, help_text='True if the diagnosis is provisional. Defaults to False', verbose_name='Provisional?'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='rhinovirus',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('positive', 'positive'), ('negative', 'negative')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='condition_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='initials',
            field=models.CharField(blank=True, help_text='The initials of the user who gave the consult.', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='reason_for_interaction_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symptomcomplex',
            name='duration',
            field=models.CharField(blank=True, choices=[('3 days or less', '3 days or less'), ('4-10 days', '4-10 days'), ('11-21 days', '11-21 days'), ('22 days to 3 months', '22 days to 3 months'), ('over 3 months', 'over 3 months')], help_text='The duration for which the patient had been experiencing these symptoms when recorded.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='drug_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='frequency_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='route_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date on which the patient began receiving this treatment.', null=True),
        ),
    ]
