# Generated by Django 2.0.9 on 2019-03-29 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odonto', '0005_auto_20190313_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='demographics',
            options={'verbose_name': 'Patient information'},
        ),
        migrations.AlterModelOptions(
            name='fp17dentalcareprovider',
            options={'verbose_name': 'Provider name, address and location'},
        ),
        migrations.AlterField(
            model_name='demographics',
            name='city_or_town',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City or town'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='house_number_or_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='House number or name'),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='performer_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Performer number'),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='provider_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provider address'),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='provider_location_number',
            field=models.CharField(blank=True, choices=[('010108', 'Albion Road'), ('010112', 'Amble'), ('010113', 'Blyth'), ('016027', 'Hexham'), ('010109', 'Longbenton'), ('24946', 'Morpeth NHS Centre'), ('010117', 'Northgate'), ('010116', 'Seaton Hirst'), ('010111', 'Wallsend'), ('010054', 'Ward 15, WGH')], max_length=255, null=True, verbose_name='Provider location'),
        ),
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provider name'),
        ),
    ]
