# Generated by Django 2.0.9 on 2019-03-29 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odonto', '0006_auto_20190329_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformerNumbers',
            new_name='PerformerNumber',
        ),
    ]
