# Generated by Django 2.0.9 on 2019-03-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0007_auto_20190329_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fp17dentalcareprovider',
            name='performer_number',
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='performer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
