# Generated by Django 2.0.9 on 2019-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0010_auto_20190402_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='antibiotic_items_prescribed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Antibiotic items prescribed'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='best_practice_prevention',
            field=models.BooleanField(default=False, verbose_name='Best practice prevention according to Delivering Better Oral Health offered'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='bridges_fitted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bridges fitted'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='crowns_provided',
            field=models.IntegerField(blank=True, null=True, verbose_name='Crowns provided'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='decayed_teeth_deciduous',
            field=models.IntegerField(blank=True, null=True, verbose_name='Decayed teeth deciduous'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='decayed_teeth_permanent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Decayed teethe permanent'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='endodontic_treatment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Endontic treatment'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='filled_teeth_deciduous',
            field=models.IntegerField(blank=True, null=True, verbose_name='Filled teeth deciduous'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='filled_teeth_permanent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Filled teeth permanent'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='fissure_sealants',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fissure sealants'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='fluoride_varnish',
            field=models.BooleanField(default=False, verbose_name='Fluoride varnish'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='lower_denture_acrylic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lower denture acrylic'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='lower_denture_metal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lower denture metal'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='missing_teeth_deciduous',
            field=models.IntegerField(blank=True, null=True, verbose_name='Missing teeth deciduous'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='missing_teeth_permanent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Missing teeth permanent'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='other_treatment',
            field=models.BooleanField(default=False, verbose_name='Other treatment'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='permanent_fillings_and_sealant_restorations',
            field=models.IntegerField(blank=True, null=True, verbose_name='Permanent fillings and sealant restorations'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='radiographs_taken',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radiographs taken'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='referral_for_advanced_mandatory_services_band',
            field=models.IntegerField(blank=True, null=True, verbose_name='Referral for advanced mandatory services band'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='scale_and_polish',
            field=models.BooleanField(default=False, verbose_name='Scale and polish'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='upper_denture_acrylic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Upper denture acrylic'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='upper_denture_metal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Upper denture metal'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='veneers_applied',
            field=models.IntegerField(blank=True, null=True, verbose_name='Veneers applied'),
        ),
        migrations.AlterField(
            model_name='fp17treatmentcategory',
            name='arrest_of_bleeding',
            field=models.BooleanField(default=False, verbose_name='Arrest of bleeding'),
        ),
        migrations.AlterField(
            model_name='fp17treatmentcategory',
            name='bridge_repairs',
            field=models.BooleanField(default=False, verbose_name='Bridge repairs'),
        ),
        migrations.AlterField(
            model_name='fp17treatmentcategory',
            name='denture_repairs',
            field=models.BooleanField(default=False, verbose_name='Denture repairs'),
        ),
        migrations.AlterField(
            model_name='fp17treatmentcategory',
            name='prescription_only',
            field=models.BooleanField(default=False, verbose_name='Prescription only'),
        ),
        migrations.AlterField(
            model_name='fp17treatmentcategory',
            name='regulation_11_replacement_appliance',
            field=models.BooleanField(default=False, verbose_name='Regulation 11 replacement appliance'),
        ),
        migrations.AlterField(
            model_name='fp17treatmentcategory',
            name='removal_of_sutures',
            field=models.BooleanField(default=False, verbose_name='Removal of sutures'),
        ),
        migrations.AlterField(
            model_name='fp17treatmentcategory',
            name='urgent_treatment',
            field=models.BooleanField(default=False, verbose_name='Urgent treatment'),
        ),
    ]
