# Generated by Django 2.0.13 on 2019-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0011_auto_20190403_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fp17clinicaldataset',
            options={'verbose_name': 'Part 5a Clinical data set'},
        ),
        migrations.AlterModelOptions(
            name='fp17dentalcareprovider',
            options={'verbose_name': 'Part 1 Provider name, address and location'},
        ),
        migrations.AlterModelOptions(
            name='fp17exemptions',
            options={'verbose_name': 'Part 4 Exemptions and remissions'},
        ),
        migrations.AlterModelOptions(
            name='fp17incompletetreatment',
            options={'verbose_name': 'Part 3 Incomplete treatment and treatment dates'},
        ),
        migrations.AlterModelOptions(
            name='fp17otherdentalservices',
            options={'verbose_name': 'Part 6 Other services'},
        ),
        migrations.AlterModelOptions(
            name='fp17recall',
            options={'verbose_name': 'Part 7 NICE guidance'},
        ),
        migrations.AlterModelOptions(
            name='fp17treatmentcategory',
            options={'verbose_name': 'Part 5 Treatment category'},
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='decayed_teeth_permanent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Decayed teeth permanent'),
        ),
        migrations.AlterField(
            model_name='fp17otherdentalservices',
            name='domicillary_services',
            field=models.BooleanField(default=False, verbose_name='Domicillary services'),
        ),
        migrations.AlterField(
            model_name='fp17otherdentalservices',
            name='free_repair_or_replacement',
            field=models.BooleanField(default=False, verbose_name='Free repair or replacement'),
        ),
        migrations.AlterField(
            model_name='fp17otherdentalservices',
            name='further_treatment_within_2_months',
            field=models.BooleanField(default=False, verbose_name='Further treatment within 2 months'),
        ),
        migrations.AlterField(
            model_name='fp17otherdentalservices',
            name='sedation_services',
            field=models.BooleanField(default=False, verbose_name='Sedation services'),
        ),
        migrations.AlterField(
            model_name='fp17otherdentalservices',
            name='treatment_on_referral',
            field=models.BooleanField(default=False, verbose_name='Treatment on referral'),
        ),
    ]
