# Generated by Django 2.0.13 on 2019-04-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0012_auto_20190425_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fp17clinicaldataset',
            options={'verbose_name': 'Clinical data set'},
        ),
        migrations.AlterModelOptions(
            name='fp17dentalcareprovider',
            options={'verbose_name': 'Performer name and clinic'},
        ),
        migrations.AlterModelOptions(
            name='fp17exemptions',
            options={'verbose_name': 'Exemptions and remissions'},
        ),
        migrations.AlterModelOptions(
            name='fp17incompletetreatment',
            options={'verbose_name': 'Incomplete treatment and treatment dates'},
        ),
        migrations.AlterModelOptions(
            name='fp17otherdentalservices',
            options={'verbose_name': 'Other services'},
        ),
        migrations.AlterModelOptions(
            name='fp17recall',
            options={'verbose_name': 'NICE guidance'},
        ),
        migrations.AlterModelOptions(
            name='fp17treatmentcategory',
            options={'verbose_name': 'Treatment category'},
        ),
        migrations.RemoveField(
            model_name='fp17incompletetreatment',
            name='treatment_band',
        ),
    ]
