# Generated by Django 2.0.13 on 2019-04-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0013_auto_20190426_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact phone number'),
        ),
    ]
