# Generated by Django 2.0.13 on 2019-04-26 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odonto', '0014_demographics_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthodonticAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('assessment_and_review', models.BooleanField(default=False)),
                ('assess_and_refuse_treatment', models.BooleanField(default=False, verbose_name='Assess & refuse treatment')),
                ('assess_and_appliance_fitted', models.BooleanField(default=False, verbose_name='Assess & appliance fitted')),
                ('iotn', models.IntegerField(blank=True, null=True, verbose_name='IOTN')),
                ('aesthetic_component', models.IntegerField(blank=True, null=True)),
                ('iotn_not_applicable', models.BooleanField(default=False, verbose_name='IOTN not applicable')),
                ('date_of_referral', models.DateField(blank=True, null=True)),
                ('date_of_assessment', models.DateField(blank=True, null=True)),
                ('date_of_appliance_fitted', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_orthodonticassessment_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_orthodonticassessment_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrthodonticDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('radiograph', models.IntegerField(blank=True, null=True)),
                ('removable_upper_appliance', models.BooleanField(default=False)),
                ('removable_lower_appliance', models.BooleanField(default=False)),
                ('fixed_upper_appliance', models.BooleanField(default=False)),
                ('fixed_lower_appliance', models.BooleanField(default=False)),
                ('function_appliance', models.BooleanField(default=False)),
                ('retainer_upper', models.BooleanField(default=False)),
                ('retainer_lower', models.BooleanField(default=False)),
                ('extractions_upper_right', models.IntegerField(blank=True, null=True)),
                ('extractions_upper_left', models.IntegerField(blank=True, null=True)),
                ('extractions_lower_right', models.IntegerField(blank=True, null=True)),
                ('extractions_lower_left', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_orthodonticdataset_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_orthodonticdataset_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrthodonticTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('patient_failed_to_return', models.BooleanField(default=False, verbose_name='Treatment abandoned - patient failed to return')),
                ('patient_requested_stop', models.BooleanField(default=False, verbose_name='Treatment abandoned - patient requested')),
                ('treatment_discontinued', models.BooleanField(default=False)),
                ('treatment_completed', models.BooleanField(default=False)),
                ('par_scores_calculated', models.BooleanField(default=False, verbose_name='PAR ')),
                ('iotn', models.IntegerField(blank=True, null=True, verbose_name='IOTN')),
                ('aesthetic_component', models.IntegerField(blank=True, null=True)),
                ('iotn_not_applicable', models.BooleanField(default=False, verbose_name='IOTN not applicable')),
                ('repair', models.BooleanField(default=False, verbose_name='Repair to appliance fitted by another dentist')),
                ('replacement', models.BooleanField(default=False, verbose_name='Regulation 11 replacement appliance')),
                ('date_of_completion', models.DateField(blank=True, null=True, verbose_name='Date of completion or last visit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_orthodontictreatment_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_orthodontictreatment_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
