# Generated by Django 2.0.9 on 2019-04-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('odonto', '0015_orthodonticassessment_orthodonticdataset_orthodontictreatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fp17dentalcareprovider',
            name='patient',
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
    ]
