# Generated by Django 2.0.9 on 2019-06-05 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
        ('odonto', '0016_auto_20190429_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('ur_1', models.BooleanField(default=False)),
                ('ur_2', models.BooleanField(default=False)),
                ('ur_3', models.BooleanField(default=False)),
                ('ur_4', models.BooleanField(default=False)),
                ('ur_5', models.BooleanField(default=False)),
                ('ur_6', models.BooleanField(default=False)),
                ('ur_7', models.BooleanField(default=False)),
                ('ur_8', models.BooleanField(default=False)),
                ('ur_9', models.BooleanField(default=False)),
                ('ur_a', models.BooleanField(default=False)),
                ('ur_b', models.BooleanField(default=False)),
                ('ur_c', models.BooleanField(default=False)),
                ('ur_d', models.BooleanField(default=False)),
                ('ur_e', models.BooleanField(default=False)),
                ('ul_1', models.BooleanField(default=False)),
                ('ul_2', models.BooleanField(default=False)),
                ('ul_3', models.BooleanField(default=False)),
                ('ul_4', models.BooleanField(default=False)),
                ('ul_5', models.BooleanField(default=False)),
                ('ul_6', models.BooleanField(default=False)),
                ('ul_7', models.BooleanField(default=False)),
                ('ul_8', models.BooleanField(default=False)),
                ('ul_9', models.BooleanField(default=False)),
                ('ul_a', models.BooleanField(default=False)),
                ('ul_b', models.BooleanField(default=False)),
                ('ul_c', models.BooleanField(default=False)),
                ('ul_d', models.BooleanField(default=False)),
                ('ul_e', models.BooleanField(default=False)),
                ('lr_1', models.BooleanField(default=False)),
                ('lr_2', models.BooleanField(default=False)),
                ('lr_3', models.BooleanField(default=False)),
                ('lr_4', models.BooleanField(default=False)),
                ('lr_5', models.BooleanField(default=False)),
                ('lr_6', models.BooleanField(default=False)),
                ('lr_7', models.BooleanField(default=False)),
                ('lr_8', models.BooleanField(default=False)),
                ('lr_9', models.BooleanField(default=False)),
                ('lr_a', models.BooleanField(default=False)),
                ('lr_b', models.BooleanField(default=False)),
                ('lr_c', models.BooleanField(default=False)),
                ('lr_d', models.BooleanField(default=False)),
                ('lr_e', models.BooleanField(default=False)),
                ('ll_1', models.BooleanField(default=False)),
                ('ll_2', models.BooleanField(default=False)),
                ('ll_3', models.BooleanField(default=False)),
                ('ll_4', models.BooleanField(default=False)),
                ('ll_5', models.BooleanField(default=False)),
                ('ll_6', models.BooleanField(default=False)),
                ('ll_7', models.BooleanField(default=False)),
                ('ll_8', models.BooleanField(default=False)),
                ('ll_9', models.BooleanField(default=False)),
                ('ll_a', models.BooleanField(default=False)),
                ('ll_c', models.BooleanField(default=False)),
                ('ll_d', models.BooleanField(default=False)),
                ('ll_e', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_extractionchart_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_extractionchart_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='fp17declaration',
            options={'verbose_name': 'Declaration'},
        ),
    ]
