# Generated by Django 2.0.9 on 2019-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0017_auto_20190605_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionchart',
            name='ll_b',
            field=models.BooleanField(default=False),
        ),
    ]
