# Generated by Django 2.0.13 on 2019-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0018_extractionchart_ll_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='performernumber',
            name='dpb_pin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='performernumber',
            name='number',
            field=models.TextField(blank=True, default=''),
        ),
    ]
