# Generated by Django 2.0.13 on 2019-07-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0019_auto_20190625_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographics',
            options={'verbose_name': 'Patient information', 'verbose_name_plural': 'Patient information'},
        ),
    ]
