# Generated by Django 2.0.13 on 2019-06-14 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odonto', '0019_auto_20190614_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformerNumber',
            new_name='Performer',
        ),
    ]
