# Generated by Django 2.0.13 on 2019-06-14 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0020_auto_20190614_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
