# Generated by Django 2.0.13 on 2019-07-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0020_auto_20190708_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='performernumber',
            name='dpb_pin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='performernumber',
            name='number',
            field=models.TextField(blank=True, default=''),
        ),
    ]
