# Generated by Django 2.0.13 on 2019-11-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0022_auto_20191025_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthodonticdataset',
            name='extractions_lower_left',
        ),
        migrations.RemoveField(
            model_name='orthodonticdataset',
            name='extractions_lower_right',
        ),
        migrations.RemoveField(
            model_name='orthodonticdataset',
            name='extractions_upper_left',
        ),
        migrations.RemoveField(
            model_name='orthodonticdataset',
            name='extractions_upper_right',
        ),
    ]
