# Generated by Django 2.0.13 on 2019-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0023_auto_20191105_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthodonticassessment',
            name='assessment',
            field=models.CharField(choices=[('Assess & review', 'Assess & review'), ('Assess & refuse treatment', 'Assess & refuse treatment'), ('Assess & appliance fitted', 'Assess & appliance fitted')], default='', max_length=256, verbose_name='Assessment Type'),
        ),
    ]
