# Generated by Django 2.0.13 on 2019-11-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0026_auto_20191128_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthodonticassessment',
            name='assess_and_appliance_fitted',
        ),
        migrations.RemoveField(
            model_name='orthodonticassessment',
            name='assess_and_refuse_treatment',
        ),
        migrations.RemoveField(
            model_name='orthodonticassessment',
            name='assessment_and_review',
        ),
    ]
