# Generated by Django 2.0.13 on 2019-12-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0027_auto_20191128_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthodonticassessment',
            name='assessment',
            field=models.CharField(choices=[('Assessment & review', 'Assessment & review'), ('Assess & refuse treatment', 'Assess & refuse treatment'), ('Assess & appliance fitted', 'Assess & appliance fitted')], default='', max_length=256, verbose_name='Assessment Type'),
        ),
    ]
