# Generated by Django 2.0.13 on 2019-12-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0027_auto_20191128_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp17treatmentcategory',
            name='treatment_category',
            field=models.CharField(blank=True, choices=[('Band 1', 'Band 1'), ('Band 2', 'Band 2'), ('Band 3', 'Band 3'), ('Urgent treatment', 'Urgent treatment'), ('Regulation 11 replacement appliance', 'Regulation 11 replacement appliance'), ('Prescription only', 'Prescription only'), ('Denture repairs', 'Denture repairs'), ('Bridge repairs', 'Bridge repairs'), ('Arrest of bleeding', 'Arrest of bleeding'), ('Removal of sutures', 'Removal of sutures')], max_length=255, null=True, verbose_name='Treatment category'),
        ),
    ]
