# Generated by Django 2.0.13 on 2019-12-16 15:43

from django.db import migrations
from django.db import transaction


@transaction.atomic
def forwards(apps, schema_editor):
    Fp17TreatmentCategory = apps.get_model('odonto', "Fp17TreatmentCategory")
    urgent_treatments = Fp17TreatmentCategory.objects.filter(urgent_treatment=True)
    urgent_treatments.filter(treatment_category=None).update(
        treatment_category="Urgent treatment"
    )
    urgent_treatments.filter(treatment_category='').update(
        treatment_category="Urgent treatment"
    )
    urgent_treatments.filter(treatment_category="Band 1").update(
        treatment_category="Urgent treatment"
    )


@transaction.atomic
def backwards(apps, schema_editor):
    Fp17TreatmentCategory.objects.filter(
        treatment_category="Urgent treatment"
    ).update(urgent_treatment=True)


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0028_auto_20191216_1405'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
