# Generated by Django 2.0.13 on 2019-12-17 16:27

from django.db import migrations
from django.db import transaction

MAPPING = {
    "Urgent treatment": "urgent_treatment",
    "Regulation 11 replacement appliance": "regulation_11_replacement_appliance",
    "Prescription only": "prescription_only",
    "Denture repairs": "denture_repairs",
    "Bridge repairs": "bridge_repairs",
    "Arrest of bleeding": "arrest_of_bleeding",
    "Removal of sutures": "removal_of_sutures"
}


@transaction.atomic
def forwards(apps, schema_editor):
    Fp17TreatmentCategory = apps.get_model('odonto', "Fp17TreatmentCategory")
    for i, v in MAPPING.items():
        Fp17TreatmentCategory.objects.filter(treatment_category=None).filter(**{v: True}).update(
            treatment_category=i
        )


@transaction.atomic
def backwards(apps, schema_editor):
    Fp17TreatmentCategory = apps.get_model('odonto', "Fp17TreatmentCategory")
    for i, v in MAPPING.items():
        Fp17TreatmentCategory.objects.filter(treatment_category=i).update(
            **{v: True}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0028_auto_20191217_1627'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]

