# Generated by Django 2.0.13 on 2019-12-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0029_auto_20191217_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fp17treatmentcategory',
            name='arrest_of_bleeding',
        ),
        migrations.RemoveField(
            model_name='fp17treatmentcategory',
            name='bridge_repairs',
        ),
        migrations.RemoveField(
            model_name='fp17treatmentcategory',
            name='denture_repairs',
        ),
        migrations.RemoveField(
            model_name='fp17treatmentcategory',
            name='prescription_only',
        ),
        migrations.RemoveField(
            model_name='fp17treatmentcategory',
            name='regulation_11_replacement_appliance',
        ),
        migrations.RemoveField(
            model_name='fp17treatmentcategory',
            name='removal_of_sutures',
        ),
        migrations.RemoveField(
            model_name='fp17treatmentcategory',
            name='urgent_treatment',
        ),
    ]
