# Generated by Django 2.0.13 on 2019-12-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0030_auto_20191217_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fp17dentalcareprovider',
            name='provider_address',
        ),
        migrations.RemoveField(
            model_name='fp17dentalcareprovider',
            name='provider_name',
        ),
    ]
