# Generated by Django 2.0.13 on 2020-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0031_auto_20191218_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthodontictreatment',
            name='resolution',
            field=models.CharField(choices=[('Treatment abandoned - patient failed to return', 'Treatment abandoned - patient failed to return'), ('Treatment abandoned - patient requested', 'Treatment abandoned - patient requested'), ('Treatment discontinued', 'Treatment discontinued'), ('Treatment completed', 'Treatment completed')], default='', max_length=256),
        ),
    ]
