# Generated by Django 2.0.13 on 2020-01-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0033_auto_20200110_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthodontictreatment',
            name='patient_failed_to_return',
        ),
        migrations.RemoveField(
            model_name='orthodontictreatment',
            name='patient_requested_stop',
        ),
        migrations.RemoveField(
            model_name='orthodontictreatment',
            name='treatment_completed',
        ),
        migrations.RemoveField(
            model_name='orthodontictreatment',
            name='treatment_discontinued',
        ),
    ]
