# Generated by Django 2.0.13 on 2020-01-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0034_auto_20200110_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orthodontictreatment',
            options={'verbose_name': 'Orthodontic Completion'},
        ),
    ]
