# Generated by Django 2.0.13 on 2020-01-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0035_auto_20200113_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orthodontictreatment',
            old_name='resolution',
            new_name='completion_type',
        ),
    ]
