# Generated by Django 2.0.13 on 2020-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0036_auto_20200113_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthodonticassessment',
            name='assessment',
            field=models.CharField(blank=True, choices=[('Assessment & review', 'Assessment & review'), ('Assess & refuse treatment', 'Assess & refuse treatment'), ('Assess & appliance fitted', 'Assess & appliance fitted')], max_length=256, null=True, verbose_name='Assessment Type'),
        ),
        migrations.AlterField(
            model_name='orthodontictreatment',
            name='completion_type',
            field=models.CharField(blank=True, choices=[('Treatment abandoned - patient failed to return', 'Treatment abandoned - patient failed to return'), ('Treatment abandoned - patient requested', 'Treatment abandoned - patient requested'), ('Treatment discontinued', 'Treatment discontinued'), ('Treatment completed', 'Treatment completed')], max_length=256, null=True),
        ),
    ]
