# Generated by Django 2.0.13 on 2020-01-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0038_auto_20200113_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthodonticassessment',
            name='iotn_field',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('N/A', 'N/A')], max_length=256, null=True, verbose_name='IOTN'),
        ),
        migrations.AddField(
            model_name='orthodontictreatment',
            name='iotn_field',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('N/A', 'N/A')], max_length=256, null=True, verbose_name='IOTN'),
        ),
    ]
