# Generated by Django 2.0.13 on 2020-01-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0040_auto_20200115_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthodonticassessment',
            name='iotn',
        ),
        migrations.RemoveField(
            model_name='orthodonticassessment',
            name='iotn_not_applicable',
        ),
        migrations.RemoveField(
            model_name='orthodontictreatment',
            name='iotn',
        ),
        migrations.RemoveField(
            model_name='orthodontictreatment',
            name='iotn_not_applicable',
        ),
    ]
