# Generated by Django 2.0.13 on 2020-01-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0041_auto_20200115_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orthodonticassessment',
            old_name='iotn_field',
            new_name='iotn',
        ),
        migrations.RenameField(
            model_name='orthodontictreatment',
            old_name='iotn_field',
            new_name='iotn',
        ),
    ]
