# Generated by Django 2.0.13 on 2020-02-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0042_auto_20200115_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp17incompletetreatment',
            name='incomplete_treatment',
            field=models.CharField(blank=True, choices=[('Band 1', 'Band 1'), ('Band 2', 'Band 2'), ('Band 3', 'Band 3')], max_length=255, null=True),
        ),
    ]
