# Generated by Django 2.0.13 on 2020-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0042_auto_20200115_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
