# Generated by Django 2.0.13 on 2020-02-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0043_fp17incompletetreatment_incomplete_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
