# Generated by Django 2.0.13 on 2020-04-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0044_demographics_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographics',
            name='patient_declined_email',
            field=models.BooleanField(default=False, verbose_name='Patient declined'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='patient_declined_phone',
            field=models.BooleanField(default=False, verbose_name='Patient declined'),
        ),
        migrations.AddField(
            model_name='fp17exemptions',
            name='commissioner_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orthodonticdataset',
            name='treatment_type',
            field=models.CharField(blank=True, choices=[('Proposed', 'Proposed'), ('Completed / Abandoned / Discontinued Treatment', 'Completed / Abandoned / Discontinued Treatment')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile phone number'),
        ),
    ]
