# Generated by Django 2.0.13 on 2020-04-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0045_auto_20200401_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientconsultation',
            options={'verbose_name': 'Clinical Notes'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Medication'},
        ),
    ]
