# Generated by Django 2.0.13 on 2020-04-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0045_auto_20200401_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientconsultation',
            options={'verbose_name': 'Clinical Notes'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Current Medication'},
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='agreed_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='provider_location_number',
            field=models.CharField(blank=True, choices=[('010108', 'Albion Road'), ('010112', 'Amble'), ('010113', 'Blyth'), ('016027', 'Hexham'), ('010109', 'Longbenton'), ('24946', 'Morpeth NHS Centre'), ('010117', 'Northgate'), ('010116', 'Seaton Hirst'), ('010111', 'Wallsend'), ('010054', 'Ward 15, WGH')], max_length=255, null=True, verbose_name='Provider location'),
        ),
    ]
