# Generated by Django 2.0.13 on 2020-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0046_auto_20200405_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientconsultation',
            options={'verbose_name': 'Clinical notes'},
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='agreed_plan',
            field=models.TextField(blank=True, default='', verbose_name='Agreed plan'),
        ),
    ]
