# Generated by Django 2.0.13 on 2020-04-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0047_auto_20200408_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Current medication'},
        ),
    ]
