# Generated by Django 2.0.13 on 2020-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0048_auto_20200415_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='aerosol_generating_procedures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orthodonticdataset',
            name='aerosol_generating_procedures',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
