# Generated by Django 2.0.13 on 2020-10-19 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0038_auto_20191206_1449'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odonto', '0049_auto_20200702_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretreatmentCovidTriageAssessments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('shielding_patient', models.IntegerField(blank=True, null=True, verbose_name='Number of assessments for a shielding patient')),
                ('increased_risk', models.IntegerField(blank=True, null=True, verbose_name='Number of assessments for a patient at increased risk of COVID')),
                ('possible_covid', models.IntegerField(blank=True, null=True, verbose_name='Number of assessments for a patient with possible/confirmed COVID-19 (or those living in the same household)')),
                ('symptom_free', models.IntegerField(blank=True, null=True, verbose_name='Number of assessments for a patient who is COVID symptom free at present')),
                ('other', models.IntegerField(blank=True, null=True, verbose_name='Number of assessments for a patient in other COVID status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_pretreatmentcovidtriageassessments_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_pretreatmentcovidtriageassessments_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COVID triage assessments',
                'verbose_name_plural': 'COVID triage assessments',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
