# Generated by Django 2.0.13 on 2020-10-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0038_auto_20191206_1449'),
        ('odonto', '0049_auto_20200702_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretreatmentCovidTriageAssessments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('triage_type', models.CharField(blank=True, choices=[('Shielding', 'Shielding'), ('Increased risk', 'Increased risk'), ('Possible COVID', 'Possible COVID'), ('Symptom free', 'Symptom free'), ('Other', 'Other')], max_length=256, null=True)),
                ('number_of_assessments', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_pretreatmentcovidtriageassessments_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_pretreatmentcovidtriageassessments_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COVID triage assessments',
                'verbose_name_plural': 'COVID triage assessments',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
