# Generated by Django 2.0.13 on 2020-11-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0051_auto_20201109_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp17dentalcareprovider',
            name='provider_location_number',
            field=models.CharField(blank=True, choices=[('Albion Road', 'Albion Road'), ('Amble', 'Amble'), ('Blyth', 'Blyth'), ('Hexham', 'Hexham'), ('Longbenton', 'Longbenton'), ('Morpeth NHS Centre', 'Morpeth NHS Centre'), ('Northgate', 'Northgate'), ('Seaton Hirst', 'Seaton Hirst'), ('Wallsend', 'Wallsend'), ('Ward 15, WGH', 'Ward 15, WGH')], max_length=255, null=True, verbose_name='Provider location'),
        ),
    ]
