# Generated by Django 2.0.13 on 2020-11-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0052_auto_20201109_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemix',
            name='access_to_oral_care',
            field=models.CharField(blank=True, choices=[('0', '0'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=256, null=True, verbose_name='Access to oral care'),
        ),
        migrations.AlterField(
            model_name='casemix',
            name='legal_and_ethical_barriers_to_care',
            field=models.CharField(blank=True, choices=[('0', '0'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=256, null=True, verbose_name='Legal and ethical barriers to care'),
        ),
    ]
