# Generated by Django 2.0.13 on 2020-11-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0052_auto_20201109_1419'),
        ('odonto', '0052_auto_20201111_1012'),
    ]

    operations = [
    ]
