# Generated by Django 2.0.13 on 2021-03-02 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0040_auto_20201007_1346'),
        ('odonto', '0055_auto_20201125_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('shielding_patient', models.IntegerField(blank=True, null=True)),
                ('increased_risk', models.IntegerField(blank=True, null=True, verbose_name='At increased risk')),
                ('possible_covid', models.IntegerField(blank=True, null=True, verbose_name='Possible/confirmed COVID-19 or lives with a possible/confirmed person')),
                ('symptom_free', models.IntegerField(blank=True, null=True)),
                ('other_covid_status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_covidstatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_covidstatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
