# Generated by Django 2.0.13 on 2021-03-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0057_auto_20210305_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemix',
            options={'verbose_name': 'Case mix', 'verbose_name_plural': 'Case mixes'},
        ),
    ]
