# Generated by Django 2.0.13 on 2021-03-12 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odonto', '0058_auto_20210305_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('date_of_contact', models.DateField(verbose_name='Date of contact')),
                ('time_of_contact', models.TimeField(verbose_name='Time the call ended')),
                ('data_care_professional', models.BooleanField(default=False, verbose_name='Carried out by a dental care professional')),
                ('primary_reason', models.CharField(blank=True, choices=[('Pain', 'Pain'), ('Swelling', 'Swelling'), ('BleedingTrauma', 'BleedingTrauma'), ('Soft tissue pathology', 'Soft tissue pathology'), ('Other', 'Other'), ('Routine treatment', 'Routine treatment')], max_length=256, null=True, verbose_name='Primary reason for call')),
                ('covid_status', models.CharField(blank=True, choices=[('Patient is shielded', 'Patient is shielded'), ('Increased risk of illness from COVID-19', 'Increased risk of illness from COVID-19'), ('Possible/confirmed COVID-19 patient (or those living in household)', 'Possible/confirmed COVID-19 patient (or those living in household)'), ('Other', 'Other'), ('Patient is COVID-19 symptom free at present', 'Patient is COVID-19 symptom free at present')], max_length=256, null=True, verbose_name='Covid status')),
                ('triage_via_video', models.BooleanField(default=False, verbose_name='Triage via video')),
                ('advice_given', models.BooleanField(default=False, verbose_name='Advice given')),
                ('advised_analgesics', models.BooleanField(default=False, verbose_name='Advised analgesics')),
                ('remote_prescription_analgesics', models.BooleanField(default=False, verbose_name='Remote prescription of analgesics')),
                ('remote_prescription_antibiotics', models.BooleanField(default=False, verbose_name='Remote prescription of antibiotics')),
                ('follow_up_call_required', models.BooleanField(default=False, verbose_name='Follow up call required')),
                ('call_back_if_symptoms_worsen', models.BooleanField(default=False, verbose_name='Recommended a call back if symptoms worsened')),
                ('referrered_to_local_udc_reason', models.CharField(blank=True, max_length=256, null=True, verbose_name='Reason the patient has been referred to the local UDC')),
                ('face_to_face_appointment', models.BooleanField(default=False, verbose_name='The triage call recommended a face to face but patient failed to attend')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_covidtriage_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_covidtriage_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Covid triage',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
