# Generated by Django 2.0.13 on 2021-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0062_auto_20210315_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidtriage',
            name='referrered_to_local_udc_reason',
            field=models.CharField(blank=True, choices=[('Life threatening emergencies', 'Life threatening emergencies'), ('Trauma', 'Trauma'), ('Oro-facial swelling', 'Oro-facial swelling'), ('Post extraction bleeding', 'Post extraction bleeding'), ('Dental conditions resulting in systematic illness', 'Dental conditions resulting in systematic illness'), ('Severe dental or facial pain', 'Severe dental or facial pain'), ('Fractured teeth with pulp exposure', 'Fractured teeth with pulp exposure'), ('Dental and soft tissue infections', 'Dental and soft tissue infections'), ('Suspected oral cancer', 'Suspected oral cancer'), ('Oro-dental conditions worsening systemic illness', 'Oro-dental conditions worsening systemic illness')], max_length=256, null=True, verbose_name='Reason the patient has been referred to the local urgent dental care centre'),
        ),
    ]
