# Generated by Django 2.0.13 on 2021-03-15 15:25

from django.db import migrations
from django.db import transaction
from odonto.episode_categories import CovidTriageEpisode

@transaction.atomic
def forwards(apps, scheme_editor):
    Patient = apps.get_model('opal', 'Patient')
    for patient in Patient.objects.all():
        patient.episode_set.create(
            category_name=CovidTriageEpisode.display_name,
            stage=CovidTriageEpisode.NEW
        )


@transaction.atomic
def backwards(apps, scheme_editor):
    Episode = apps.get_model('opal', 'Episode')
    Episode.objects.filter(
        category_name=CovidTriageEpisode.display_name
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0059_covidtriage'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]

