# Generated by Django 2.0.13 on 2021-03-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0063_auto_20210315_1459'),
        ('odonto', '0064_auto_20210315_1525'),
    ]

    operations = [
    ]
