# Generated by Django 2.0.13 on 2021-03-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0065_merge_20210315_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidtriage',
            old_name='data_care_professional',
            new_name='dental_care_professional',
        ),
    ]
