# Generated by Django 2.0.13 on 2021-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0066_auto_20210317_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidtriage',
            name='triage_type',
            field=models.CharField(blank=True, choices=[('FP17', 'FP17'), ('FP17O', 'FP17O')], max_length=256, null=True),
        ),
    ]
