# Generated by Django 2.0.13 on 2021-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0067_covidtriage_triage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidtriage',
            name='date_of_contact',
        ),
        migrations.RemoveField(
            model_name='covidtriage',
            name='time_of_contact',
        ),
        migrations.AddField(
            model_name='covidtriage',
            name='datetime_of_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of contact'),
        ),
    ]
