# Generated by Django 2.0.13 on 2021-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0068_auto_20210325_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidtriage',
            name='primary_reason',
            field=models.CharField(blank=True, choices=[('Pain', 'Pain'), ('Swelling', 'Swelling'), ('Bleeding', 'Bleeding'), ('Trauma', 'Trauma'), ('Soft tissue pathology', 'Soft tissue pathology'), ('Other', 'Other'), ('Routine treatment', 'Routine treatment')], max_length=256, null=True, verbose_name='Primary reason for call'),
        ),
    ]
