# Generated by Django 2.0.13 on 2021-08-31 12:22

from django.db import migrations
from odonto import constants


def forwards(apps, *args, **kwargs):
    Role = apps.get_model("opal", "Role")
    Role.objects.get_or_create(
        name=constants.DENTAL_ADMINISTRATOR
    )


def backwards(apps, *args, **kwargs):
    Role = apps.get_model("opal", "Role")
    Role.objects.filter(
        name=constants.DENTAL_ADMINISTRATOR
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0069_auto_20210804_1504'),
    ]

    operations = [
        migrations.RunPython(
            forwards, reverse_code=backwards
        )
    ]
