# Generated by Django 2.0.13 on 2021-11-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0071_auto_20211115_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fp17clinicaldataset',
            old_name='permanent_fillings_and_sealant_restorations',
            new_name='permanent_fillings',
        ),
    ]
