# Generated by Django 2.0.13 on 2021-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0072_auto_20211115_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='advanced_perio_root_surface_debridement',
            field=models.IntegerField(blank=True, null=True, verbose_name='Advanced perio root surface debridement'),
        ),
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='pre_formed_crowns',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pre-Formed Crowns'),
        ),
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='permanent_fillings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Permanent fillings'),
        ),
    ]
