# Generated by Django 2.0.13 on 2021-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0073_auto_20211115_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='custom_made_occlusal_appliance',
            field=models.CharField(blank=True, choices=[('Hard', 'Hard'), ('Soft', 'Soft')], max_length=256, null=True, verbose_name='Custom made occlusal appliance'),
        ),
    ]
