# Generated by Django 2.0.13 on 2022-04-04 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odonto', '0074_auto_20211130_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fp17Commissioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('flexible_commissioning_flag', models.CharField(blank=True, choices=[('Securing Access for Urgent Care', 'Securing Access for Urgent Care'), ('Promoting Access to Routine Care', 'Promoting Access to Routine Care'), ('Providing Care of High Needs Groups', 'Providing Care of High Needs Groups'), ('Starting Well', 'Starting Well'), ('Enhanced Health in Care Homes', 'Enhanced Health in Care Homes'), ('Collaboration in Local Care Networks', 'Collaboration in Local Care Networks')], max_length=255, null=True, verbose_name='Flexible commissioning flag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_odonto_fp17commissioning_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_odonto_fp17commissioning_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
