# Generated by Django 2.2.16 on 2022-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0076_auto_20220405_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='molar_endodontic_treatment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Molar endodontics'),
        ),
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='non_molar_endodontic_treatment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Non-molar endodontics'),
        ),
    ]
