# Generated by Django 2.2.16 on 2022-09-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0076_auto_20220405_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='highest_bpe_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('-', '-'), ('0 with furcation', '0 with furcation'), ('1 with furcation', '1 with furcation'), ('2 with furcation', '2 with furcation'), ('3 with furcation', '3 with furcation'), ('4 with furcation', '4 with furcation')], max_length=256, null=True, verbose_name='Highest BPE Sextant Score'),
        ),
    ]
