# Generated by Django 2.2.16 on 2022-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0076_auto_20220405_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp17clinicaldataset',
            name='untreated_decayed_teeth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Untreated decayed teeth'),
        ),
    ]
