# Generated by Django 2.2.16 on 2022-10-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0077_auto_20220930_1607'),
        ('odonto', '0077_auto_20221003_1423'),
    ]

    operations = [
    ]
