# Generated by Django 2.0.13 on 2022-10-05 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odonto', '0078_merge_20221003_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDentalProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdc_number', models.CharField(max_length=256)),
                ('dcp_type', models.CharField(choices=[('Therapist', 'Therapist'), ('Hygienist', 'Hygienist'), ('Dental Nurse', 'Dental Nurse'), ('Clinical Technician', 'Clinical Technician')], max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fp17dentalcareprovider',
            name='associated_dcp',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Associated dental professional'),
        ),
    ]
