# Generated by Django 2.0.13 on 2022-10-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0079_auto_20221005_0936'),
        ('odonto', '0079_auto_20221005_2030'),
    ]

    operations = [
    ]
