# Generated by Django 2.2.16 on 2022-10-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0080_merge_20221007_0914'),
        ('odonto', '0077_auto_20221003_0749'),
    ]

    operations = [
    ]
