# Generated by Django 2.0.13 on 2022-10-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0077_auto_20221003_0749'),
        ('odonto', '0080_merge_20221007_0914'),
    ]

    operations = [
    ]
