# Generated by Django 2.2.16 on 2022-10-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0081_merge_20221009_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='patient_declined_email',
            field=models.BooleanField(blank=True, default=False, verbose_name='Patient declined'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='patient_declined_phone',
            field=models.BooleanField(blank=True, default=False, verbose_name='Patient declined'),
        ),
    ]
