# Generated by Django 2.2.16 on 2022-11-07 14:27

from django.db import migrations
from django.db import transaction

FROM_TO = {
    "0 with furcation": "0",
    "1 with furcation": "1",
    "2 with furcation": "2",
    "3 with furcation": "3",
    "4 with furcation": "4",
}


@transaction.atomic
def forwards(apps, schema_editor):
    Fp17ClinicalDataSet = apps.get_model('odonto', "Fp17ClinicalDataSet")
    for from_value, to_value in FROM_TO.items():
        Fp17ClinicalDataSet.objects.filter(
            highest_bpe_score=from_value
        ).update(
            highest_bpe_score=to_value
        )

class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0082_auto_20221017_2054'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
