# Generated by Django 2.2.16 on 2022-11-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0083_bpe_welsh_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp17clinicaldataset',
            name='highest_bpe_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('-', '-')], max_length=256, null=True, verbose_name='Highest BPE Sextant Score'),
        ),
    ]
