# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-30 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCDS1Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-claim_number',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='BCDS1MessageSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, b'Sent'), (1, b'Success'), (2, b'Failure')])),
                ('response', models.TextField()),
                ('ordering', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bcds1_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='odonto_submissions.BCDS1Message')),
            ],
            options={
                'ordering': ('ordering',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('name',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract_number', models.IntegerField(unique=True)),
                ('provider_number', models.IntegerField(unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('name',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_xml', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
        migrations.AddField(
            model_name='performer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='odonto_submissions.Provider'),
        ),
        migrations.AddField(
            model_name='bcds1messagesubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcds1_message_submissions', to='odonto_submissions.Submission'),
        ),
        migrations.AddField(
            model_name='bcds1message',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcds1_messages', to='odonto_submissions.Provider'),
        ),
        migrations.AlterUniqueTogether(
            name='bcds1messagesubmission',
            unique_together=set([('submission', 'ordering')]),
        ),
        migrations.AlterUniqueTogether(
            name='bcds1message',
            unique_together=set([('provider', 'claim_number')]),
        ),
    ]
