# Generated by Django 2.0.13 on 2019-04-25 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCDS1Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_xml', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('serial_number', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('Unsent', 'Unsent'), ('Sent', 'Sent'), ('Success', 'Success'), ('Failure', 'Failure')], default='Unsent', max_length=256)),
                ('response', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'serial_number',
            },
        ),
        migrations.CreateModel(
            name='SystemClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odonto_submissions.SystemClaim'),
        ),
        migrations.AddField(
            model_name='submission',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odonto_submissions.BCDS1Message'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('message', 'serial_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bcds1message',
            unique_together={('episode', 'user')},
        ),
    ]
