# Generated by Django 2.0.9 on 2019-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcds1messagesubmission',
            name='state',
            field=models.IntegerField(choices=[(0, 'Sent'), (1, 'Success'), (2, 'Failure')]),
        ),
    ]
