# Generated by Django 2.0.13 on 2019-04-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'get_latest_by': 'serial_number', 'ordering': ('-serial_number',)},
        ),
    ]
