# Generated by Django 2.0.13 on 2019-07-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('odonto_submissions', '0002_auto_20190425_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Success', 'Success'), ('Failed to send', 'Failed to send'), ('Rejected by compass', 'Rejected by compass')], default='', max_length=256),
        ),
    ]
