# Generated by Django 2.0.13 on 2019-07-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0002_auto_20190425_1114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bcds1message',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bcds1message',
            name='user',
        ),
    ]
