# Generated by Django 2.0.13 on 2019-07-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0002_auto_20190425_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcds1message',
            options={'get_latest_by': 'created', 'ordering': ('created',), 'verbose_name': 'BCDS1 Message'},
        ),
        migrations.AlterUniqueTogether(
            name='bcds1message',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bcds1message',
            name='user',
        ),
    ]
