# Generated by Django 2.0.13 on 2019-07-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('odonto_submissions', '0002_auto_20190425_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'get_latest_by': 'submission_number', 'ordering': ('-submission_number',)},
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='serial_number',
            new_name='submission_number',
        ),
        migrations.AddField(
            model_name='submission',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odonto_submissions.SystemClaim'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Success', 'Success'), ('Failed to send', 'Failed to send'), ('Rejected by compass', 'Rejected by compass')], default='', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('episode', 'submission_number')},
        ),
    ]
