# Generated by Django 2.0.13 on 2019-06-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0003_auto_20190612_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcds1message',
            name='episode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
        ),
        migrations.AlterUniqueTogether(
            name='bcds1message',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bcds1message',
            name='user',
        ),
    ]
