# Generated by Django 2.0.13 on 2019-07-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0004_auto_20190723_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='message',
        ),
    ]
