# Generated by Django 2.0.13 on 2019-07-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0005_remove_submission_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bcds1message',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bcds1message',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='bcds1message',
            name='user',
        ),
        migrations.DeleteModel(
            name='BCDS1Message',
        ),
    ]
