# Generated by Django 2.0.13 on 2019-08-29 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0005_auto_20190729_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompassBatchResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(default='')),
                ('state', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='compasss_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odonto_submissions.CompassBatchResponse'),
        ),
    ]
