# Generated by Django 2.0.13 on 2019-07-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('odonto_submissions', '0006_auto_20190723_1812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('episode', 'serial_number')},
        ),
    ]
