# Generated by Django 2.0.13 on 2019-07-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0007_auto_20190723_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odonto_submissions.SystemClaim'),
        ),
    ]
