# Generated by Django 2.0.13 on 2019-07-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0009_compassbatchresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemclaim',
            options={'ordering': ('-reference_number',)},
        ),
    ]
