# Generated by Django 2.0.13 on 2019-09-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0010_auto_20190724_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compass_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odonto_submissions.CompassBatchResponse'),
        ),
        migrations.AddField(
            model_name='submission',
            name='rejection',
            field=models.TextField(blank=True, default=''),
        ),
    ]
