# Generated by Django 2.0.13 on 2019-09-25 14:06

from django.db import migrations
from django.db import connection


class Migration(migrations.Migration):
    # sqlite doesn't support atomic table renaming
    atomic = not connection.vendor == 'sqlite'

    dependencies = [
        ('odonto_submissions', '0011_auto_20190924_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemClaim',
            new_name='Transmission',
        ),
    ]
