# Generated by Django 2.0.13 on 2019-09-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0012_auto_20190925_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmission',
            options={'ordering': ('-transmission_id',)},
        ),
        migrations.RenameField(
            model_name='transmission',
            old_name='reference_number',
            new_name='transmission_id',
        ),
    ]
