# Generated by Django 2.0.13 on 2019-09-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0013_auto_20190925_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='claim',
            new_name='transmission',
        ),
    ]
