# Generated by Django 2.0.13 on 2019-09-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('odonto_submissions', '0014_auto_20190925_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'get_latest_by': 'submission_count', 'ordering': ('-submission_count',)},
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='serial_number',
            new_name='submission_count',
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('episode', 'submission_count')},
        ),
    ]
