# Generated by Django 2.0.13 on 2019-10-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0015_auto_20190925_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='response',
            new_name='request_response',
        ),
    ]
