# Generated by Django 2.0.13 on 2019-10-24 13:34

from django.db import migrations
from django.db import connection


class Migration(migrations.Migration):
    # sqlite doesn't support atomic table renaming
    atomic = not connection.vendor == 'sqlite'

    dependencies = [
        ('odonto_submissions', '0016_auto_20191024_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompassBatchResponse',
            new_name='Response',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='compass_response',
            new_name='response',
        ),
    ]
