# Generated by Django 2.0.13 on 2020-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0017_auto_20191024_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Success', 'Success'), ('Failed to send', 'Failed to send'), ('Rejected by compass', 'Rejected by compass'), ('Manually Processed', 'Manually Processed')], default='', max_length=256),
        ),
    ]
