# Generated by Django 2.0.13 on 2022-06-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0019_episodesbeinginvestigated'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('New', 'New'), ('Replace', 'Replace'), ('Delete', 'Delete')], default='New', max_length=256),
        ),
    ]
