# Generated by Django 2.0.13 on 2022-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto_submissions', '0019_episodesbeinginvestigated'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesbeinginvestigated',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
