on: [push, pull_request]
jobs:
  # run python/js tests, coveralls and lint
  test:
    name: Integration test ${{ matrix.os }} python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        python-version:
        - 3.7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up ruby for coveralls
        uses: actions/setup-ruby@v1
      - name: Set up js
        uses: actions/setup-node@v1
      - name: Install js dependencies
        run: npm install jasmine-core@2.3.4 karma@1.5 karma-coverage@1.1.1 karma-jasmine@0.3.8 karma-firefox-launcher@2.1.0 karma-coveralls@1.1.2
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install opal with workflows
        run: pip install -e git+https://github.com/openhealthcare/opal@work-flows#egg=opal
      - run: gem install coveralls-lcov
      - run: gem install rake
      - name: run tests
        run: opal test --coverage
      - name: flake8
        run: flake8
      - name: combine coveralls
        run: find coverage -name "lcov.info" -exec coveralls-lcov -v -n {} \; > coverage/coverage.json
      - run: coveralls --merge=coverage/coverage.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
